## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
#Mon May 25 02:07:28 MDT 2026
android.builtInKotlin=true
android.disableLastStageWhenHiltIsApplied=true
android.enableAndroidTest=false
android.enableJetifier=false
android.enableUnitTest=false
android.ndkVersion=29.0.14206865
android.nonTransitiveRClass=true
android.useAndroidX=true
aurafx.skip.tests=true
kotlin.builtInKotlin=true
ksp.incremental=false
ksp.kotlinApiVersion=2.3
ksp.kotlinLanguageVersion=2.3
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding\=UTF-8 -Djava.awt.headless\=true -Dkotlin.daemon.jvm.options\="-Didea.force.use.core.classloader\=true,-Xmx10240M"
org.gradle.parallel=true
org.gradle.workers.max=2
